spring:
  datasource:
    url: jdbc:h2:file:./data/tasks
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  h2:
    console.enabled: true